services:
  - type: web
    name: likhog-frontend
    env: static
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: client/build
    headers:
      - path: /*
        headers:
          - key: X-Frame-Options
            value: DENY
    routes:
      - type: rewrite
        source: /(.*).js
        destination: /$1.js
      - type: rewrite
        source: /(.*).css
        destination: /$1.css
      - type: rewrite
        source: /static/(.*)
        destination: /static/$1
      - type: rewrite
        source: /*
        destination: /index.html
